// Builds module launch parts and their services for an Apple build.
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

/** Writes a generated SwiftPM target with each module's `apple/launch/*.swift`
 * and a registry of their `ExactLaunchPart` types, in `launch` order. SwiftPM
 * needs it inside the package. Returns its directory, or null if there are none. */
export function writeLaunchParts(pkg, app) {
  const modules = app.launch;
  if (!modules.some(m => m.launch.length)) return null;
  const dir = resolve(pkg, '.launch-parts', app.id);
  mkdirSync(dir, { recursive: true });
  const keep = new Set(['Registry.swift']), types = [];
  const put = (name, text) => { const to = resolve(dir, name); if (!existsSync(to) || readFileSync(to, 'utf8') !== text) writeFileSync(to, text); };
  for (const m of modules) for (const f of m.launch) {
    const text = readFileSync(f, 'utf8');
    for (const match of text.matchAll(/(?:struct|class|enum)\s+(\w+)\s*:[^{]*\bExactLaunchPart\b/g)) types.push(match[1]);
    keep.add(`${m.name}-${basename(f)}`);
    put(`${m.name}-${basename(f)}`, text);
  }
  put('Registry.swift', `// Generated by host/apple/build.mjs from app.json launch; never committed.\nimport ExactKit\n\npublic enum ExactLaunchParts {\n    public static let all: [ExactLaunchPart.Type] = [${types.map(t => `${t}.self`).join(', ')}]\n}\n`);
  for (const f of readdirSync(dir)) if (!keep.has(f)) rmSync(resolve(dir, f));
  return dir;
}

/** Each launch module's `apple/service/*.swift`, built as its own dylib.
 * ExactKit loads it when the launch part's policy says, never during launch. */
export const launchServices = (modules, buildDir) => modules.filter(m => m.service.length)
  .map(m => ({ name: m.name, load: `lib${m.name}_service.dylib`, built: resolve(buildDir, `lib${m.name}_service.dylib`), sources: m.service }));

/** swiftc's arguments for a service dylib, before its target. */
export const serviceArgs = svc => ['-parse-as-library', '-emit-library', '-O', '-swift-version', '5', '-module-name', `ExactService_${svc.name}`, ...svc.sources, '-lsqlite3', '-o', svc.built];

/** Throws unless the linked launch parts have at most 32 KiB of text and data
 * and no static initializer or ObjC +load, which would run outside the timed
 * `launch()` call. */
export function auditLaunchParts(object, modules, read) {
  if (!existsSync(object)) return;
  const [, row] = (read('xcrun', ['size', object]).stdout ?? '').trim().split('\n');
  const [text, data] = (row ?? '').trim().split(/\s+/).map(Number);
  const sections = read('otool', ['-l', object]).stdout ?? '';
  const problems = [];
  if (text + data > 32768) problems.push(`${text + data} bytes of text and data, over the 32 KiB budget`);
  if (/sectname (__mod_init_func|__init_offsets)/.test(sections)) problems.push('a static initializer (it runs before launch, outside the timed call)');
  if (/sectname __objc_nl(cls|cat)list/.test(sections)) problems.push('an Objective-C +load');
  if (problems.length) throw new Error(`host/apple: module launch parts (app.json launch): ${problems.join('; ')}`);
  console.log(`host/apple: launch parts ${modules.map(m => m.name).join(', ')}: ${text + data} B, no initializers`);
}
