[package]
workspace = "../../../snapback4"
name = "messages-legacy-apple"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]
exact-logic = { path = "../../../logic" }
exact-snapback4 = { path = "../../../snapback4" }
serde_json = "1.0"
exact-apple = { path = "../../../host/apple" }
exact-js = { path = "../../../js" }

[build-dependencies]
snapback4-lang.workspace = true
serde_json = "1.0"
exact-js-bake = { path = "../../../js/bake" }

[dev-dependencies]
snapback4-core.workspace = true
exact-kernel = { path = "../../../kernel" }
exact-plan = { path = "../../../plan" }
exact-runner = { path = "../../../runner" }
exact-js-value = { path = "../../../js/value" }
serde_json = "1.0"
